# Architecture
TARGET_BOARD_SUFFIX := _32
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_BOARD_PLATFORM := lc1860
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := cortex-a7

# Partitions
# 注意：这里的大小故意改大，是为了骗过编译系统的打包检查。
# 实际上手机的分区大小由分区表决定，不用管这里。
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 16777216
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1073741824
BOARD_USERDATAIMAGE_PARTITION_SIZE := 17179869184
BOARD_FLASH_BLOCK_SIZE := 131072
TARGET_USERIMAGES_USE_EXT4 := true

# prebuilt kernel
TARGET_PREBUILT_KERNEL := device/leadcore/lte26007/kernel
BOARD_KERNEL_CMDLINE := console=ttyS1,115200n8
BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_PAGESIZE := 2048

# Recovery
TARGET_RECOVERY_FSTAB := device/leadcore/lte26007/recovery.fstab
DEVICE_RESOLUTION := 720x1280
RECOVERY_GRAPHICS_USE_LINELENGTH := true
BOARD_HAS_LARGE_FILESYSTEM := true
RECOVERY_SDCARD_ON_DATA := true
RECOVERY_VARIANT := twrp

# TWRP 极限瘦身配置 (为了塞进 3MB 分区)
TW_EXCLUDE_SUPERSU := true
TW_EXCLUDE_TWRPAPP := true
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_USE_TOOLBOX := true
TW_NO_SCREEN_BLANK := true
TW_NO_NANO_EDITOR := true
TW_NO_EXFAT_FUSE := true
TW_NO_BASH := true
TW_NO_BUSYBOX_SYMLINKS := true
TW_EXCLUDE_ENCRYPTED_BACKUPS := true

TW_BRIGHTNESS_PATH := "/sys/class/leds/lcd-backlight/brightness"